job_logging:
  loggers:
    large_gcs:
      level: DEBUG
    drake:
      level: WARNING
    # Set the entire planning_through_contact package to DEBUG
    planning_through_contact:
      level: DEBUG