repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.6.9
  hooks:
    - id: ruff
      args: [--fix]
    - id: ruff-format
- repo: https://github.com/floatingpurr/sync_with_poetry
  rev: 1.1.0
  hooks:
    - id: sync_with_poetry
      args: [
          '--all',  # Scan all dependencies in poetry.lock (main and dev)
      ]
